name: Tag Runner
on:
  push:
    branches:
      - 'ci/**'

jobs:
  build_artifacts:
    name: Process tags
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      BRANCH_NAME: ${{ github.head_ref }}
      LATEST_TAG_FILE: "latest_tag.txt"
      RELEASE_VERSION: ${{ secrets.GITHUB_RUN_ID }}
      MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      PACKAGE_NAME: ${{ secrets.APP_PACKAGE }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get and set name of current branch
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Display current branch name
        run: echo ${BRANCH_NAME}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Download pyproject.toml
        run: curl -L https://raw.githubusercontent.com/masgeek/py-github/develop/pyproject.toml -o pyproject.toml

      - name: Download Tag fetching script
        run: curl -L https://raw.githubusercontent.com/masgeek/py-github/develop/fetch-tags.py -o latest-tag.py

      - name: Install dependencies with Poetry
        run: poetry install --no-root

      - name: Fetch latest tag
        run: poetry run python latest-tag.py
