<?php

namespace app\models;

use \app\models\base\Country as BaseCountry;

/**
 * This is the model class for table "countries".
 */
class Country extends BaseCountry
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
