<?php

namespace app\models;

use \app\models\base\DiseaseReportImage as BaseDiseaseReportImage;

/**
 * This is the model class for table "disease_report_images".
 */
class DiseaseReportImage extends BaseDiseaseReportImage
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
