<?php

namespace app\models;

use \app\models\base\DiseaseReport as BaseDiseaseReport;

/**
 * This is the model class for table "disease_reports".
 */
class DiseaseReport extends BaseDiseaseReport
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
